pipeline {
  agent any

  stages {
    stage('Checkout') {
      steps {
        checkout scm
      }
    }

    stage('Detect Changes') {
      steps {
        script {
          def files = sh(
            script: "git diff --name-only HEAD~1 HEAD",
            returnStdout: true
          ).trim().split('\n')

          env.BE_CHANGED = files.any { it.startsWith('AI_Contact_BE/') } ? 'true' : 'false'
        }
      }
    }

    stage('Push Repo to GitHub') {
      steps {
        sshagent(['github-ssh']) {
          sh '''
            git remote add github git@github.com:Spinichi/commontest.git || true
            git push github HEAD:master --force
          '''
        }
      }
    }

    stage('Deploy Backend') {
      when {
        expression { return env.BE_CHANGED == 'true' }
      }
      steps {
          dir('AI_Contact_BE') {
            withCredentials([
              file(credentialsId: 'my-env-file',   variable: 'ENV_PATH'),
              file(credentialsId: 'my-properties', variable: 'PROP_PATH')
            ]) {
              sh '''
                cp "$ENV_PATH" .env
                chmod 644 .env
              '''
              sh '''
                mkdir -p src/main/resources
                cp "$PROP_PATH" src/main/resources/application.properties
                chmod 644 src/main/resources/application.properties
              '''
              sh 'docker-compose down || true'
              sh 'docker-compose up -d --build --force-recreate'
            }
          }
      }
    }
  }

//   post {
//     failure {
//       mail to: 'spinichi@naver.com',
//            subject: "[CI FAILURE] ${env.JOB_NAME}",
//            body: "Build/Deployment error : ${env.BUILD_URL}"
//     }
//   }
}